### ISSUE TITLE
ombi dev builds new search bar for movies.

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#16]
breaks the search bar a bit.

this seems to fix it. 
```css
.search-bar-background[_ngcontent-c1] {
    background-color: #0000 !important;
}
.form-control-search[_ngcontent-c1] {
    width: 100% !important;
}
```
