### ISSUE TITLE
Org Settings page top nav different height.

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#21]
THE PROBLEM:
![](https://cdn.discordapp.com/attachments/537824268336103434/542873834055794703/unknown.png)

THE FIX:
![](https://cdn.discordapp.com/attachments/537824268336103434/542873760860995594/unknown.png)

```css
.bg-title {
    padding-top: 0px;
    padding-bottom: 0px;
}
```
