### ISSUE TITLE
This shit

### ISSUE THREAD

**Issue by goldenpipes** [Archmonger/Blackberry-Themes#35]
```css
#customCSSEditor, div[id$=FavIcon] textarea {
  height: -webkit-fill-available !important;
  border-radius: 3px;
  font-size: 12px;
  font-weight: 400;
}
```

![lTj4u6gmhc](https://user-images.githubusercontent.com/6140137/59698068-8b605d80-91b4-11e9-9fc1-800dfa3ba35c.gif)
