### ISSUE TITLE
Custom Login Wallpaper

### ISSUE THREAD

**Issue by Majibear** [Archmonger/Blackberry-Themes#48]
I love the themes, but is there any way to keep your own custom Login Page wallpaper?

**Comment by Archmonger** [comment]
Hey Majibear,

Thanks for making me aware of the UX need for custom login wallpapers.

Due to the way these themes are designed, you'll need to use custom CSS for this.
For example, in Organizr Custom CSS you can type in:
```css
.login-register {
     background: url("https://www.sciencemag.org/sites/default/files/styles/article_main_large/public/dogs_1280p_0.jpg") center center/cover no-repeat !important; 
}
```
^ On the above example, edit the URL to any link of your choosing. If you need additional help, feel free to chat in our [#support channel on Discord](https://discord.gg/sfjkDaM)

I will be updating the [customization wiki page](https://github.com/Archmonger/Blackberry-Themes/wiki/Organizr-Theme-Customization) soon to add a variable for customizing this in the future.

**Comment by Majibear** [comment]
That worked great, thanks!

**Comment by Archmonger** [comment]
I have simplified the process to change the login screen background image. Here's an example code snippet.

```css
:root {
    --login-bg: url("https://archmonger.github.io/Blackberry-Themes/Resources/blur-noise.png");
}
```

See our [wiki page](https://github.com/Archmonger/Blackberry-Themes/wiki/Organizr-Theme-Customization#example-changing-the-login-screen-background-to-an-image) for more details.
